### ISSUE TITLE
Does not work with 1920x1200 screens

### ISSUE THREAD

**Issue by beren12** [KevinTyrrell/FishingBot#32]
It can't find the bobber, manual calibration doesn't help, and auto calibrate counts down to 1 then stops and does nothing.

**Comment by beren12** [comment]
I'm using the latest oracle java and it works fine if I set the resolution to 1920x1080

**Comment by KevinTyrrell** [comment]
@beren12 Thank you.

Do me a favor. Open `cmd.exe` by typing `cmd` into the windows search bar.

Type `java --version` and ensure it prints something along the lines of `Java(TM) SE Runtime Environment`.

Navigate to the directory that `FishingBot.jar` is located at. For example if it was on your desktop, you would write `cd C:/users/<username>/desktop/` where `<username>` is your windows username.

Afterwards, type `dir` and ensure `FishingBot.jar` shows up in the results. Then type `java -jar FishingBot.jar`. This should open the program up as if you clicked on it normally. Perform the same steps as before for calibrating and see if your `cmd` window shows any kind of error or exception being thrown. Copy the entire thing and paste it here.

Thank you.

**Comment by beren12** [comment]
```
C:\WINDOWS\system32>java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)```

**Comment by beren12** [comment]
```
C:\WINDOWS\system32>java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)```

**Comment by beren12** [comment]
```
c:\Users\chris\Desktop>java -jar FishingBot.jar
Exception in thread "Thread-6" java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
        at sun.awt.image.IntegerInterleavedRaster.getDataElements(Unknown Source)
        at java.awt.image.BufferedImage.getRGB(Unknown Source)
        at model.Angler.calibrate(Angler.java:229)
        at controller.Controller.lambda$calibrate$0(Controller.java:80)
        at java.lang.Thread.run(Unknown Source)```

**Comment by beren12** [comment]
That's the error in 1920x1200

**Comment by beren12** [comment]
If you need help testing this, you should be able to do it from a 2nd machine. set 1920x1200 as a custom resolution in your graphics card control panel, install parsec. connect to your machine with parsec from another machine and change the resolution to 1920x1200 and you'll get black bars on the left and right and it'll work just scaled down a little. when you disconnect it'll go back to 1080p or whatever resolution you had.

**Comment by beren12** [comment]
I have a batch file that does "c:\Program Files\QRes.exe" -x:1920 -y:1200
and downloaded qres from the internet.

**Comment by beren12** [comment]
Any chance you have time to work on this at all?
